name: rundb

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
          
      - name: Run docker-compose up
        working-directory: ./mimgrdb
        run: docker-compose up -d

      - name: Ensure containers are still running
        run: |
          if [ $(docker-compose ps -q | wc -l) -eq 0 ]; then
            echo "No containers are running. Exiting..."
            exit 1  # Explicitly fail the job if no containers are running
          fi
        working-directory: ./mimgrdb

      - name: Get Docker logs on failure
        if: failure()
        run: docker-compose logs
        working-directory: ./mimgrdb
