name: rundb

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
          
      - name: Run docker-compose up
        run: |
          echo "Running docker-compose for 15 seconds..."
          timeout 15 docker-compose up
          RESULT=$?  # Capture the exit code of the timeout command

          # Check the exit code
          if [ $RESULT -ne 124 ]; then
              exit 1
          fi
        working-directory: ./mimgrdb

      - name: Get Docker logs on failure
        if: failure()
        run: docker-compose logs
        working-directory: ./mimgrdb
